# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  GLFW_config = debug_x64
  glad_config = debug_x64
  ImGui_config = debug_x64
  raylib_config = debug_x64
  Core_config = debug_x64
  Appl_config = debug_x64

else ifeq ($(config),debug_x86)
  GLFW_config = debug_x86
  glad_config = debug_x86
  ImGui_config = debug_x86
  raylib_config = debug_x86
  Core_config = debug_x86
  Appl_config = debug_x86

else ifeq ($(config),release_x64)
  GLFW_config = release_x64
  glad_config = release_x64
  ImGui_config = release_x64
  raylib_config = release_x64
  Core_config = release_x64
  Appl_config = release_x64

else ifeq ($(config),release_x86)
  GLFW_config = release_x86
  glad_config = release_x86
  ImGui_config = release_x86
  raylib_config = release_x86
  Core_config = release_x86
  Appl_config = release_x86

else ifeq ($(config),dist_x64)
  GLFW_config = dist_x64
  glad_config = dist_x64
  ImGui_config = dist_x64
  raylib_config = dist_x64
  Core_config = dist_x64
  Appl_config = dist_x64

else ifeq ($(config),dist_x86)
  GLFW_config = dist_x86
  glad_config = dist_x86
  ImGui_config = dist_x86
  raylib_config = dist_x86
  Core_config = dist_x86
  Appl_config = dist_x86

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW glad ImGui raylib Core Appl

.PHONY: all clean help $(PROJECTS) App Core Dependencies

all: $(PROJECTS)

App: Appl

Core: Core

Dependencies: GLFW ImGui glad raylib

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C vendors/glfw -f Makefile config=$(GLFW_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C vendors/glad -f Makefile config=$(glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C vendors/imgui -f Makefile config=$(ImGui_config)
endif

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C vendors/raylib -f Makefile config=$(raylib_config)
endif

Core: ImGui
ifneq (,$(Core_config))
	@echo "==== Building Core ($(Core_config)) ===="
	@${MAKE} --no-print-directory -C projects/core -f Makefile config=$(Core_config)
endif

Appl: Core ImGui
ifneq (,$(Appl_config))
	@echo "==== Building Appl ($(Appl_config)) ===="
	@${MAKE} --no-print-directory -C projects/appl -f Makefile config=$(Appl_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendors/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C vendors/glad -f Makefile clean
	@${MAKE} --no-print-directory -C vendors/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C vendors/raylib -f Makefile clean
	@${MAKE} --no-print-directory -C projects/core -f Makefile clean
	@${MAKE} --no-print-directory -C projects/appl -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  dist_x64"
	@echo "  dist_x86"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   glad"
	@echo "   ImGui"
	@echo "   raylib"
	@echo "   Core"
	@echo "   Appl"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"